apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}-controller-manager-metrics-monitor
  labels:
    control-plane: controller-manager
  {{- include "helm.labels" . | nindent 4 }}
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: sreportal
      control-plane: controller-manager
