apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-portal-admin-role
  labels:
  {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - sreportal.my.domain
  resources:
  - portals
  verbs:
  - '*'
- apiGroups:
  - sreportal.my.domain
  resources:
  - portals/status
  verbs:
  - get
