apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "helm.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "helm.fullname" . }}-serving-cert
  labels:
  {{- include "helm.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "helm.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-sreportal-my-domain-v1alpha1-dns
  failurePolicy: Fail
  name: vdns-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sreportal.my.domain
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsrecords
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "helm.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-sreportal-my-domain-v1alpha1-portal
  failurePolicy: Fail
  name: vportal-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sreportal.my.domain
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - portals
  sideEffects: None
