apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-web-mcp-service
  labels:
    control-plane: controller-manager
  {{- include "helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webMcpService.type }}
  selector:
    app.kubernetes.io/name: sreportal
    control-plane: controller-manager
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webMcpService.ports | toYaml | nindent 2 }}
