---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-sreportal-my-domain-v1alpha1-dns
  failurePolicy: Fail
  name: mdns-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sreportal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dns
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-sreportal-my-domain-v1alpha1-portal
  failurePolicy: Fail
  name: mportal-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sreportal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - portals
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sreportal-my-domain-v1alpha1-dns
  failurePolicy: Fail
  name: vdns-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sreportal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dns
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-sreportal-my-domain-v1alpha1-portal
  failurePolicy: Fail
  name: vportal-v1alpha1.kb.io
  rules:
  - apiGroups:
    - sreportal.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - portals
  sideEffects: None
