# This rule is not used by the project sreportal itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to sreportal.my.domain resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sreportal
    app.kubernetes.io/managed-by: kustomize
  name: portal-viewer-role
rules:
- apiGroups:
  - sreportal.my.domain
  resources:
  - portals
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sreportal.my.domain
  resources:
  - portals/status
  verbs:
  - get
