# apiVersion: sreportal.io/v1alpha1
# kind: Portal
# metadata:
#   labels:
#     app.kubernetes.io/name: sreportal
#     app.kubernetes.io/managed-by: kustomize
#   name: main
#   namespace: sreportal-system
# spec:
#   title: "Main Portal"
#   main: true
# ---
apiVersion: sreportal.io/v1alpha1
kind: Portal
metadata:
  labels:
    app.kubernetes.io/name: sreportal
    app.kubernetes.io/managed-by: kustomize
  name: loc-1
  namespace: sreportal-system
spec:
  title: "loc 1"
  subPath: "loc-1"
